### ISSUE TITLE
Demonstrate how to use announce responses to establish new data channels

### ISSUE THREAD

**Issue by anacrolix** [backkem/gowttest#1]
It's not clear how to generate a data channel from the announce responses. It's not clear why announce responses contain offer or answer, or what the importance of the offer_id is.

**Comment by backkem** [comment]
Hi @anacrolix, Thanks for looking into this. As you surely noticed this code is in a very early stage. I'll try to work on this some more this week. To already give you an idea:
- WebRTC establishes a connection by exchanging an offer for an answer between two peers.
  - Example when of creating an offer: [data-channels-create](https://github.com/pion/webrtc/tree/master/examples/data-channels-create)
  - Example when receiving an offer: [data-channels](https://github.com/pion/webrtc/tree/master/examples/data-channels)
- announce responses can contain an answer if it's a peer responding to your offer.
- announce responses can contains an offer if it's a peer trying to open a new connection with you. In this case you have to respond with the answer.
- offer_id helps you determine to which offer an answer belongs to.
- pion/webrtc allows you to 'detach' a datachannel to give you a more ideomatic way to work with it, example: [detach](https://github.com/pion/webrtc/tree/master/examples/data-channels-detach)

**Comment by backkem** [comment]
Hi @anacrolix, I extended the example to address your questions. It's missing a lot of error handling etc, but I hope it now serves as a decent basic example. It's now up to the point where we start speaking BT protocol, I'll leave that up to you ;) Hopefully the detached data-channel (implements ReadWriteCloser interface) fits nicely into your existing codebase.

Feel free to ask any more questions you may have!

**Comment by anacrolix** [comment]
In the example, you only create a single offer ID. Can you handle multiple answers to the same offer ID by creating new peer connections as required?

Why should the `SettingEngine` with `DetachDataChannels` be global?

**Comment by backkem** [comment]
- Offers: no, if you increase 'numwant' in your announcement, you need to create the same amount of peerconnections which will all give you an offer for which you create a unique offer ID and add all of this to the 'offers' slice in the announcement.
- API object: My comment just meant to say you can create the API object once and create multiple peerconnections under it. It's just a little optimization, it doesn't have to be an actual global variable, just create it once.

**Comment by backkem** [comment]
It seems we should try to mold this into a net.Listener for use in `anacrolix/torrent`.
